### ISSUE TITLE
Adding a component to the Demo application

### ISSUE THREAD

**Issue by saschwarz** [survivejs/react-component-boilerplate#19]
I imported my component into the ``Demo.jsx`` file as ``import SVGPathPlayer from '../src/svgplayer.jsx';``
My component, in turn, imports it's styling via a Sass scss file: ``import './svgplayer.scss';`` and imports a 3rd party lib (snap.svg) which requires a custom loader. I've added the loaders to the appropriate build targets.

I get this traceback when running ``npm run dist``:
```
> webpack

/Users/saschwarz/dev/react-svgpathplayer/node_modules/babel-core/lib/transformation/file/index.js:671
      throw err;
      ^
SyntaxError: /Users/saschwarz/dev/react-svgpathplayer/src/svgplayer.scss: Unexpected token (1:0)
> 1 | .svg-player {
    | ^
  2 |     border: 1px solid #d3d3d3;
  3 |     .buttons {
  4 |         border-top: 1px solid #d3d3d3;
```
After some dividing/conquering of the ``webpack.config.babel.js`` file I found the problem is caused by:
``import App from './demo/App.jsx';`` which pulls in ``Demo.jsx`` which then brings in my component and the unsupported files.

So for now I've disabled that import, and consequently the demo functionality, and everything now compiles/runs correctly. It would be nice to re-enable the demo feature; but I'm not sure what the best solution would be. 

For my purposes using the dist build of the component and manually inserting the script tags for the externals into a plain HTML file to create a demo is probably easier than the custom build step with templated insertion of the extracted bundles. I also like the idea that only one build of the component exists and it is used everywhere so I won't ever have to debug different build permutations; but I'm still new to webpack so that solution is also easiest for me to grok...

Another solution would be to not import ``App`` into ``webpack.config.babel.js`` and find another way to supply the template with the ``App`` component.

The last solution I can think of is to find another way to import my component into the ``Demo.jsx``.

I'd greatly appreciate your input; I'm wondering if I'm not using the demo feature of this boilerplate as you intended.

**Comment by bebraw** [comment]
Can you set up a little standalone example for me to try out? I have a rough idea of what might be going on. Just need to verify my hunch and figure out a neat solution. :+1:

**Comment by saschwarz** [comment]
Maybe the easiest would be for me to fork this project, add an import of a Saas stylesheet to Demo.jsx and add the loader to the webpack config. Would that work?

As a side question how did you know that webpack would find the webpack.config.babel.js file and would causes webpack to preprocess it? I couldn't find mention of it in the webpack docs.

**Comment by bebraw** [comment]
> Maybe the easiest would be for me to fork this project, add an import of a Saas stylesheet to Demo.jsx and add the loader to the webpack config. Would that work?

Sounds reasonable.

> As a side question how did you know that webpack would find the webpack.config.babel.js file and would causes webpack to preprocess it? I couldn't find mention of it in the webpack docs.

It's a little known feature. The docs don't seem to cover it all.

**Comment by saschwarz** [comment]
I've created the clone/branch as I proposed - I had to disable the pre-push test/linting to allow it to commit: https://github.com/saschwarz/react-component-boilerplate/tree/demo

**Comment by bebraw** [comment]
@saschwarz Would it work for you if you moved `import './demo.scss';` from `app/Demo.jsx` to `app/index.js`? That avoids the issue while allowing you to style still. An alternative would be to pass scss through [null-loader](https://www.npmjs.com/package/null-loader) in that `dev` configuration.

**Comment by saschwarz** [comment]
I just set up the sccs file in the demo as the easiest way to demonstrate the problem. 

In my actual components I put the sccs file(s) in the src directory and import them into my jsx files in the src/ directory. Then my component is imported into the Demo.jsx. So my problem isn't styling the demo it is using any number of loaders in my components or needing specific externals to make 3rd party libs behave:
```
  externals: {
   ...
   'snapsvg': 'var Snap'
  },
```
Any of those make the build fail due to the ``App`` import.

I can commit my actual (small) component probably by Friday it that would help.

**Comment by bebraw** [comment]
> I can commit my actual (small) component probably by Friday if it that would help.

Ok. Let's get back to it on Friday. I think the most likely scenario is that we'll need to use `noop-loader` for stubbing out the behavior. That way it simply does nothing when it finds a scss file.

**Comment by saschwarz** [comment]
I've checked in my component to a branch using the boilerplate that shows the traceback with both Sass and a 3rd party library when running the ``npm run`` commands:
https://github.com/saschwarz/react-svgpathplayer

Let me know if there is anything else I can do.

**Comment by bebraw** [comment]
I noticed that your repo is missing `lib/`. There's a little `postinstall` script the build depends on so it's good include. The idea is that it allows people to consume a development version of your library by pointing at git. The script will then kick in and generate a build for them.

I also had to hit `npm i classnames lodash -S` to get the missing dependencies. After that I could use `npm run`.

The error it throws has to do with `import App from './demo/App.jsx';` we use at Webpack configuration. Effectively it tries to process `import './svgpathplayer.scss';` through Babel, which will obviously fail as it's not something Babel understands.

That `import Snap from 'snapsvg';` is problematic as well given it has dependency on `window`. `window` doesn't exist on back-end side so this would need some kind of a kludge as well.

## Solution

One obvious way to solve this would be to process the isomorphic bit of the boilerplate through Webpack. That would sidestep the problem effectively.

If you don't care about isomorphism, you could disable the import for now and tweak the setup to operate in "old fashioned" way (just SPA). This would mean using `0.6.0` kind of setup or so.

I don't have time to fix this properly for a while as I'm really busy with my book at the moment...

**Comment by saschwarz** [comment]
Thanks for investigating and finding those issues with my package (I missed those moving from another boilerplate I was using). The lib dir was missing due to a global gitignore.
Just a quick clarification; even with those dependencies installed ``npm run dist`` only works if I remove the `import App` from webpack's config.

Thanks for the pointer to your 0.6.0 version I'll take a look at it since I only need client rendering at this time.

**Comment by bebraw** [comment]
> Just a quick clarification; even with those dependencies installed npm run dist only works if I remove the import App from webpack's config.

Yeah, that's to be expected.

Maybe I could make it easier to enable/disable client-only rendering. The requirements of isomorphic rendering are quite hard for certain cases.
