### ISSUE TITLE
ES Lint Errors strict mode not permitted

### ISSUE THREAD

**Issue by saschwarz** [survivejs/react-component-boilerplate#20]
I get these errors when running ``npm run lint``:
```
~/dev/react-component-boilerplate $ npm run lint

> react-component-boilerplate@1.1.3 lint /Users/saschwarz/dev/react-component-boilerplate
> eslint . --ext .js --ext .jsx

The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.

/Users/saschwarz/dev/react-component-boilerplate/demo/index.js
  1:1  error  Strict mode is not permitted  strict

/Users/saschwarz/dev/react-component-boilerplate/lib/deploy_gh_pages.js
  1:1  error  Strict mode is not permitted  strict

/Users/saschwarz/dev/react-component-boilerplate/src/index.js
  1:1  error  Strict mode is not permitted  strict

/Users/saschwarz/dev/react-component-boilerplate/webpack.config.babel.js
  1:1  error  Strict mode is not permitted  strict

✖ 4 problems (4 errors, 0 warnings)
```
Did you want to update the ``.eslintrc`` to specify ``"strict": 0``? 

I'm not certain how to resolve: ``The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.`` I couldn't find where that is specified in the branch and ``jsx-quotes`` is already specified in the ``.eslintrc``.

**Comment by bebraw** [comment]
`react/jsx-quotes` was moved to core as `jsx-quotes`. Are you sure it isn't picking up global ESLint or something? I can't reproduce this locally.

I don't think that `"strict": 0` should be needed. These days all files are strict by default (ES6) so I don't use `use strict` declarations anymore.

**Comment by saschwarz** [comment]
Those files do have 'use strict;' on their first line:
https://github.com/survivejs/react-component-boilerplate/blob/master/demo/index.js#L1
https://github.com/survivejs/react-component-boilerplate/blob/master/webpack.config.babel.js#L1

**Comment by bebraw** [comment]
@saschwarz Those are redundant. Fixed. Thanks!
