### ISSUE TITLE
Can't run `dist` task.

### ISSUE THREAD

**Issue by raphaelparent** [survivejs/react-component-boilerplate#21]
I downloaded this boilerplate and modified a couple thing (removed the renderJSX from the webpack config, render the component directly in the body, etc.). And now I'm trying tp run `npm run dist` and i get an error.

```
ERROR in ./demo/App.jsx
Module parse failed: /Users/rparent/Documents/CTSProjects/cem/modules/boilerplate/demo/App.jsx Line 2: Unexpected token
You may need an appropriate loader to handle this file type.
| 
| import React from 'react';
| import Fork from 'react-ghfork';
| import pkgInfo from '../package.json';
 @ ./src/index.js 3:13-39
``` 

And this is the content of the App.jsx file.
```
import React from 'react';
import Fork from 'react-ghfork';
import pkgInfo from '../package.json';

export default class App extends React.Component {
  render() {
    return (
      <div>
        <p>This is some text</p>
      </div>
    );
  }
}
```

I'm not familiar with webpack and npm scripts yet so this might a really small thing somewhere that I forgot.

I can provide more code if you want.

Thanks :smiley:

**Comment by bebraw** [comment]
Yeah, a GitHub project would be ideal. I can have a look at this tomorrow.

**Comment by raphaelparent** [comment]
Perfect!

I just pushed everything on github, here's the [link](https://github.com/raphaelparent/react-component-boilerplate-example).

**Comment by raphaelparent** [comment]
Well I think I found out why, I'm trying to require my component in the `src/index.js`  and it doesn't like that. What I want to do eventually is to push this component on NPM to be used within other projects. Any quick ideas on how to do that?

**Comment by bebraw** [comment]
Would `var Component = require('../Component');` kind of import work? The current expects to find the file from the same directory. Just a quick guess.

Alternatively you could try to develop it below `src/` directly (or rename?). I'm not entirely sure what splitting it up between `src` and `component` achieves.

**Comment by raphaelparent** [comment]
I was working with the same structures that you have, with demo and src. I'll try that.

**Comment by raphaelparent** [comment]
So yeah this is working, it runs `npm run dist` without errors.

Another of my concerns is that I can't seem to be able to import css into `Component.jsx`, the import only works in the `component/index.js` file. Since I want to export the component has a complete standalone module I want it to work directly in the `Component.jsx`. 

Do you have an idea on how I should modify this to make it work?

**Comment by bebraw** [comment]
CSS handling is somewhat problematic at the moment. There isn't single right way to handle it. Just see the [Styling React](http://survivejs.com/webpack_react/styling_react/) chapter of my book to get some idea.

Bundling the style to `dist` might be a little problematic as we cannot make any assumptions about how our packages are consumed. This is the reason why I like to include a sample CSS file to the project root. You can then import that through Webpack at least if nothing else.

Of course I'm willing to improve the setup if a better solution comes along. For now dealing with styling is a bit messy.

**Comment by raphaelparent** [comment]
Ok perfect, thank you for your time this is really appreciated!

I will go css file at the project root because that seems to be the most logic way to go for now.

**Comment by bebraw** [comment]
Alright, enjoy. :+1:
