### ISSUE TITLE
running the gh-pages npm command does nothing

### ISSUE THREAD

**Issue by mvanlonden** [survivejs/react-component-boilerplate#24]
This is the output followed by no changes in the `gh-pages` branch and no directory called `gh-pages` created

```
➜  react-selection-popover master ✗ npm run gh-pages

> react-selection-popover@0.0.3 gh-pages /react-selection-popover
> webpack

reading file /react-selection-popover/README.md
```

**Comment by bebraw** [comment]
Thanks for letting me know. I'll get that fixed. It likely has something to do with html-webpack-plugin and remark. Feels like a version issue.

**Comment by mvanlonden** [comment]
I think I found the issue but not the cause. 

My README looks like this (changed closing backticks to `'''`)
```
# react-selection-popover
Popover menu for selected text

## Getting started

Add the `SelectionPopover` component to the div that contains the selectable text. Add the `data-selectable` attribute to the same div.

Add any children and props (including styling) to `SelectionPopover`.
```js
  import React from 'react';
  import SelectionPopover from 'react-selection-popover'

  export default class Demo extends React.Component {
    render() {
      return (
        <div data-selectable>
          I am selectable text!
          <SelectionPopover>
            <button>save</button>
            <button>share</button>
          </SelectionPopover>
        </div>
      )
    }
  }
'''

## Contributing

Clone repo then
```sh
npm install
npm start
'''

### TODO
- add tests
- disable user selection for children of popover

## License

*react-selection-popover* is available under MIT. See LICENSE for more details.
```

It started working again when I deleted the second code block section
```
```sh
npm install
npm start
'''
```

I didn't add shell to the list of languages in `HtmlWebpackRemarkPlugin`. Tried adding `bash` and it still didn't work. Fine for now as I changed the second code block to `js` for the time being

**Comment by bebraw** [comment]
Okay, that makes perfect sense. It has to do with this declaration:

```javascript
      new HtmlWebpackRemarkPlugin({
        key: 'documentation',
        file: config.paths.readme,
        languages: {
          js
        }
      }),
```

To fix, you should do

```javascript
import sh from 'highlight.js/lib/languages/sh';
import js from 'highlight.js/lib/languages/javascript';
```

and pass `sh` to the plugin. It might be `bash` too.

I think I'll port the site to [Catalog](https://github.com/interactivethings/catalog) as it's nice for React projects. You can see it in action [here](http://reactabular.js.org/).

In addition to eliminating the issue it gives us something nicer to work with. I'll close this issue once I have done the work.
