### ISSUE TITLE
Noticed a couple of issues while trying to use it

### ISSUE THREAD

**Issue by godspeed20** [survivejs/react-component-boilerplate#30]
1. it seems to be missing a package (probably due to dependency changes over time). Need to add 

    "loader-utils": "^0.2.16",

to your package.json

2. the GithubCorner icon your code generates requires there to be a 'user' param in the package.json that isn't there by default (figured out through guessing tbh) so might be worth adding a 

  "user": "survivejs",

to your package.json too

**Comment by bebraw** [comment]
Hi,

I updated the dependencies. Can you give it a go?

That 1. is weird as webpack should pick it up. Can you see which package needs it? 2. should be set already.

**Comment by godspeed20** [comment]
2. correct, my bad.

1. still happens for me. clean checkout, no error when I npm install but when I npm start (no code changes, just your boilerplate) it fails with that error:

ERROR in Cannot find module 'loader-utils'
 @ ./docs/index.jsx 36:13-36
Child html-webpack-plugin for "index.html":

index.jsx hasn't much on that line, just a var reference to an empty map. Maybe i'm misreading the code though, unless it's Catalog doing it which you'd think would fix itself via npm install anyway. 

Anyway no biggy, the project is still a huge help, Just thought I'd mention it as I saw the issue when trying to test it out.

**Comment by godspeed20** [comment]
hmm actually it is a subdependency for a quite a few of the package.json dependencies, I can see it downloading in various places. possibly there's a dodgy bit of code in one of the packages that is looking in the parent node_modules folder for the package rather than it's own local one, Catalog for example has no dependency on that module, not sure it actually needs it internally though

**Comment by bebraw** [comment]
Which version of node/npm are you running?

**Comment by godspeed20** [comment]
turns out a pretty old one, will get that upgraded :|

**Comment by bebraw** [comment]
Ah, alright. Thanks for letting me know.

npm 3, Node 6 is a good combo.

**Comment by godspeed20** [comment]
yup, upgraded and the error has gone (damn you bill gates, should not have taken me half an hour to install an app due to MS magic!)
