### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by ayushinigam** [survivejs/react-component-boilerplate#33]
Commands npm run dist:modules and npm run dist are successful in my component repo,
When I do a yarn add file:'../path' and add my component to my react project
and run the project it fails during compilation and displays the error `You may need an appropriate loader to handle this file type`
It's failing to compile JSX in my component file.
<img width="482" alt="screen shot 2017-05-27 at 7 58 32 pm" src="https://cloud.githubusercontent.com/assets/16535047/26522128/fd624c0c-4316-11e7-8c6a-6f4569fe6a3b.png">

**Comment by bebraw** [comment]
Hi,

Can you link to the repository? There might be some configuration missing.

**Comment by ayushinigam** [comment]
Thanks for the quick reponse. Here is the repo link: [https://github.com/ayushinigam/react-google-map-street-view](url)

**Comment by bebraw** [comment]
Can you give exact commands to run? I'm doing this wrong somehow.

**Comment by ayushinigam** [comment]
This is the component library and I am just doing npm start 
The problem occurs when I do a yarn add of this repo to my react project

**Comment by bebraw** [comment]
Ah, like that. I didn't design the boilerplate with `yarn add` in mind so it might be missing something. It should work if you consume it through Git, though. I wonder what's the right fix.

**Comment by bebraw** [comment]
Ok, I see the problem now. I've set `"module": "src",` wrong. I have to change that.

**Comment by bebraw** [comment]
The fix is to use Babel to generate such version that transpiles everything except ES6 modules. I'll do this fix in the boilerplate within an hour or so.

**Comment by bebraw** [comment]
Hi,

There's an initial fix if you want to try. Perhaps it can be simplified somehow. PR welcome.

**Comment by ayushinigam** [comment]
Thanks! I will try this, also do I need to make any changes in the webpack.config as well?

**Comment by ayushinigam** [comment]
Hi! Can you please check with the changes in .babelrc, npm start is failing

**Comment by bebraw** [comment]
It's just Babel and **package.json** changes.

**Comment by bebraw** [comment]
Just fixed `npm start` too. Babel configuration gets tricky due to `env` and the way it behaves (no proper overrides).

**Comment by ayushinigam** [comment]
Perfect, works now! 👍 
Thanks!
