### ISSUE TITLE
Serverside rendring compatibility

### ISSUE THREAD

**Issue by ImanMh** [survivejs/react-component-boilerplate#34]
Is it possible to build components with this boilerplate that support server side rending? I see this error when I import my component: 

```
...\dist\manifest.js:152
/******/ ([]);
         ^
ReferenceError: window is not defined
```

**Comment by bebraw** [comment]
Can you link to a small example? I would need more information to understand what's going on.

**Comment by ImanMh** [comment]
Since it happens on server side rendering I don't know how to provide an example for you. All I can say is that if you have a page that is using react server-side rendering and you add `<GoogleTagManager />` script to it it will throw that error which clearly says `window is not defined ` because window is not present in Nodejs environment.

**Comment by bebraw** [comment]
It's impossible for me to say why it fails. There's not enough information. Maybe some other boilerplate would fit your purposes better? I maintain this one quite randomly and it's far from popular. 😄

**Comment by bebraw** [comment]
@ImanMh Any luck with this? I would need a project to study to say anything concrete.

**Comment by ImanMh** [comment]
@bebraw Sorry for delay I will try to create a repo that demonstrate this issue today.

**Comment by ImanMh** [comment]
Please run the following:
```
git clone git@github.com:ImanMh/test-react-component-boilerplate.git
cd test-react-component-boilerplate
npm i
vim src/routes/home/Home.js
# line 13 and 30 are important take a look at them then exit the vim
npm start
```

Now there is an error sounds like I couldn't even use the boilerplate. What do you think is the issue?

component repo: https://github.com/ImanMh/test-react-component-boilerplate
project repo: https://github.com/ImanMh/serverside-issue-demonstration

**Comment by bebraw** [comment]
Would it be possible for you to use some other boilerplate instead? It might be the time to deprecate this one as I don't have resources to maintain it.

**Comment by ImanMh** [comment]
sure thanks. I think the concepts behind your work is amazing. When it comes to create a react component these are the things that are a pain and I rather not to handle my self:  

1. Making gh-pages is hard your idea about automating this part is brilliant
2. Adding test framework and managing basic dependencies  is also a waste of time 
3. Common tasks that you added like linting is also a grate feature 

If you are about to create an other repo and deprecate this one please address the above issues. I will be your first user. Thank you.

**Comment by bebraw** [comment]
Look into [nwb](https://www.npmjs.com/package/nwb) and [mrm](https://www.npmjs.com/package/mrm). We are using latter for [webpack-defaults](https://www.npmjs.com/package/webpack-defaults) and I think it solves the aforementioned problems better than any boilerplate can due to support for migrations.
