### ISSUE TITLE
Missing class properties transform.

### ISSUE THREAD

**Issue by daviestar** [survivejs/react-component-boilerplate#36]
<img width="518" alt="screen shot 2017-07-25 at 08 40 52" src="https://user-images.githubusercontent.com/959906/28561136-11046570-7115-11e7-89eb-b5297f7db3cb.png">

Hello, I've tried everything, now I'm here begging for help.

I can't seem to add support for es7 class properties using this boilerplate, I'm using this:

```js
"presets": [
    "react",
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "transform-runtime",
    "transform-class-properties"
  ],
```
and I've tried every order of those I can imagine.  Any ideas?

**Comment by bebraw** [comment]
Can you push a project to study? Technically it should be a change along that, yup. I would avoid Stage 0 as that's dangerous (you never know what you are going to get with that).

Note that I'm considering dropping support for the boilerplate as it's a better idea to go with solutions like [nwb](https://www.npmjs.com/package/nwb) or [mrm](https://www.npmjs.com/package/mrm).

**Comment by daviestar** [comment]
@bebraw thanks for the reply.

I tried `nwb` and it worked first time, and has loads of features I hadn't even really considered!  Thanks for the pointer, I'll use that now.  

I'll close this, but if you want to check support for es7 class properties, just start a new `react-component-boilerplate` project with the following:

_src/index.js_
```js
import React, {Component} from 'react'

export default class TestComponent extends Component {
  
  state = {
    number: 1
  }

  incrementNumber = () => {
     this.setState({number: this.state.number++})
  }
  
  render() {
    return (
      <div onClick={this.incrementNumber}>
        {this.state.number}
      </div>
    )
  }
}

```
