### ISSUE TITLE
Consider adding storybook

### ISSUE THREAD

**Issue by alebrozzoSP** [survivejs/react-component-boilerplate#38]
It would be nice to have storybook added to the boilerplate so to check components as being developed. I particularly don't use github pages but I think it only allows for a single repo to be deployed, so anyone with multiple projects would have trouble dealing with it.

**Comment by bebraw** [comment]
That would be a bigger change. Now it's on Catalog. I can accept a PR for this, though.

**Comment by alebrozzo** [comment]
Sorry, what is Catalog? something like Storybook?

**Comment by bebraw** [comment]
Yeah, Catalog is roughly like Storybook. Just not as popular. Both have their sides.

**Comment by bebraw** [comment]
I think I'll skip this one. Replacing Catalog with Storybook would be fairly simple but probably not worth the effort. Catalog is good enough.
