### ISSUE TITLE
I get an error when running command BABEL_ENV=es6

### ISSUE THREAD

**Issue by alebrozzoSP** [survivejs/react-component-boilerplate#39]
I am a Windows dev (please don't shun me) and running scripts on `package.jsn` that have the setting `BABEL_ENV=xxx` causes an error. Also happens with `rimraf`, which I can overcome with replacing it with `del-cli` package.

Please consider making the scripts Windows friendly ;)

**Comment by alebrozzoSP** [comment]
I just installed `cross-env` and it seems to work for handling env variables... would you accept a PR where I change both rimraff and env variable setting using `del-cli` and `cross-env`? I would not be able to test on something other than Windows though

**Comment by bebraw** [comment]
Sure, please PR.
