### ISSUE TITLE
Error: spawn catalog.js-start ENOENT

### ISSUE THREAD

**Issue by szare** [survivejs/react-component-boilerplate#41]
After starting I recieve the following error:

Error: spawn catalog.js-start ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-component-boilerplate@6.1.2 start: `catalog start docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-component-boilerplate@6.1.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by bebraw** [comment]
Which version of Node/npm are you using? I cannot reproduce the issue. You should have npm5 and Node 8 at least.

**Comment by szare** [comment]
Hi bebraw,
Node: 8.9.1
Npm: 5.5.1
OS: Windows 10

**Comment by bebraw** [comment]
@szare Can you pull the newest version, re-install the dependencies, and give it another go?

I don't have Win 10 available unfortunately.

**Comment by szare** [comment]
@bebraw following error:
spawn catalog.js-start ENOENT

**Comment by bebraw** [comment]
I don’t know how to fix this (no access to Win). Perhaps you can find some other boilerplate and/or report the issue to Catalog.

**Comment by szare** [comment]
I created an issue in Catalog:
[https://github.com/interactivethings/catalog/issues/343](https://github.com/interactivethings/catalog/issues/343)
